# Quasi-polynomial systems

```{r, include=FALSE}
source("common_settings.R")
```

**Lesson plan**:

1. We discuss a fairly general class of dynamical systems, called "Quasi-Polynomial" (QP-)systems. 
1. We show how any QP-system can be written as a larger-dimensional Generalized Lotka-Volterra model. 
1. This means that the machinery we built for analyzing GLV models can be used to tackle a variety of models that at face value do not seem to fall in this class. We show how to determine global stability in several ecological and epidemiological models using this method.
1. This also shows that the GLV model is in a way a "universal" model.
1. For a simple application, we examine models of metapopulation dynamics with ecosystem engineering.

## Global stability

Many dynamical models of ecological, epidemiological and evolutionary systems have equilibria that are globally stable (e.g., SIR, SIS, logistic growth, Levins' metapopulation model, MacArthur's consumer-resource model). 

By far, the most powerful method to prove the global stability of an equilibrium is the so-called "Lyapunov direct method", which we've encountered several times already. The main drawback of this method is that devising an appropriate Lyapunov function requires ingenuity---and as Strogatz put it---"divine inspiration". Here we take a different approach: we turn our model of interested into a (possibly larger) GLV model, and then attempt applying the typical Lyapunov function for GLV to our transformed system. In practice, this will require us to think carefully about how perturbations in the original system translate into the (larger) GLV.

We first show how systems that are in "Quasi-Polynomial" (QP) form can be embedded into a larger GLV by means of simple matrix operations. Then, we show that other models can be turned into QP, and from there into GLV.

## From QP to GLV

We call a Quasi-Polynomial system a system of $n$ ODEs that can be written as:

$$
\frac{d x_i(t)}{d t} = x_i(t) \left(s_i + \sum_{j = i}^m A_{ij} \prod_{k=1}^n x_k(t)^{B_{jk}}\right)
$$
where $s$ is a vector of "growth rates" (not necessarily positive), $A$ is a matrix of interactions, and $B$ a matrix of exponents. Note that if we take $B = I_n$ (the identity matrix), we recover the GLV model. If $B$ contains only integers, then we recover a polynomial system. Extending this model to real (but not necessarily integer) numbers $B_{jk}$, we have a "quasi-polynomial" system (@hernandez1998algebraic).

In general, we assume that $A$ is of size $n \times m$, $B$ is $m \times n$, and that the $x_i(t)$ are real and positive (if that's not the case, one needs to perform a change of variables that ensures positivity). The system has $n$ variables (the $x_i(t)$), and we can identify $m$ "quasi-monomials":

$$
\prod_{k=1}^n x_k^{B_{jk}}
$$

Several models in ecology and evolution belong to this class. For example, a model that departs from the GLV family is the so-called Leslie-Gower model:

$$
\begin{cases}
\dfrac{d H}{dt} = H(\rho_h - \alpha_h P - \beta_h H)\\
\dfrac{d P}{dt} = P \left(\rho_p - \alpha_p \dfrac{P}{H} \right)
\end{cases}
$$

The equation for the prey ($H$) is in GLV form. However, the rate of increase (decrease) of the predator depends on the ratio between predators and prey: when prey are abundant, the predator grows with rate close to $\rho_p$; if prey are scarce, on the other hand, the predator declines. 

Solving for the coexistence equilibrium, we find:

$$
\begin{cases}
H^\star = \dfrac{\alpha_p \rho_h}{\alpha_p \beta_h + \alpha_h \rho_p}\\
P^\star = \dfrac{\rho_p \rho_h}{\alpha_p \beta_h + \alpha_h \rho_p}
\end{cases}
$$

Note that the model is in QP-form. We recognize three monomials:

$$
\begin{pmatrix}
H\\
P\\
\dfrac{P}{H}
\end{pmatrix}
=
\begin{pmatrix}
H^1 P^0\\
H^0 P^1\\
H^{-1}P^1
\end{pmatrix}
$$

And the associated parameters:

$$
s = (\rho_h, \rho_p) \quad A = \begin{pmatrix} -\beta_h & -\alpha_h & 0\\ 0 & 0 & -\alpha_p \end{pmatrix} \quad B = \begin{pmatrix} 1 & 0 \\ 0 & 1 \\ -1 & 1 \end{pmatrix}
$$

Now we want to turn this models into a Generalized Lotka-Volterra model. We take the new variables to be our monomials:

$$
z = 
\begin{pmatrix}
z_1\\
z_2\\
z_3
\end{pmatrix}
=
\begin{pmatrix}
H^1 P^0\\
H^0 P^1\\
H^{-1}P^1
\end{pmatrix}
$$
and transform the growth rates:

$$
r = \begin{pmatrix}
r_1\\
r_2\\
r_3
\end{pmatrix} = B s = \begin{pmatrix}
\rho_h\\
\rho_p\\
\rho_p - \rho_h
\end{pmatrix}
$$

and the matrix of interactions:

$$
M = B A = \begin{pmatrix}
-\beta_h & -\alpha_h & 0\\
0 & 0 & -\alpha_p\\
\beta_h & \alpha_h & -\alpha_p\
\end{pmatrix}
$$

The GLV system is clearly equivalent (topologically) to the original system, but has now three equations instead of two. Using the transformation $r = Bs$, $M = BA$ you can embed any QP system into a (typically, larger) GLV.

## Stability of GLV

Before proceeding to prove the stability of the coexistence equilibrium for the Leslie-Gower model, we need to revisit the Lyapunov function for the GLV introduced by @goh1977global, which we have encountered before. Take a GLV:

$$
\dfrac{d z}{d t} = D(z)(r + M z) = D(z)(M(z - z^\star)) = D(z)M\Delta z
$$

where $\Delta z$ is a vector of deviations from the equilibrium. Suppose that all species densities remain positive through the dynamics; then, we can write the dynamics of the logarithm of the species densities (where $\log z$ is a vector containing the logarithms of the densities):

$$
\dfrac{d \log z}{d t} = r + M z = M \Delta z
$$

We can take the function:

$$
V = 1^T D(c)(z - z^\star - D(z^\star) \log (z/z^\star))
$$
where $D(c)$ is a diagonal matrix with positive diagonal coefficients. Deriving wrt time, we find:

$$
\dfrac{dV}{dt} = 1^T D(c) \left( \dfrac{dz}{dt} - D(z^\star) \dfrac{d\log z}{d t} \right)
$$

substituting:

$$
\dfrac{dV}{dt} = 1^T D(c) \left( D(x) M \Delta z  - D(z^\star) M \Delta z \right) = 
1^T D(c) D(\Delta z) M \Delta z
$$

Because diagonal matrices commute (i.e., $D_1 D_2 = D_2 D_1$), we can write:

$$
\dfrac{dV}{dt} = 1^T D(\Delta z) D(c) M \Delta z
$$

and finally, we absorb the $D(\Delta z)$:

$$
\dfrac{dV}{dt} = \Delta z^T D(c) M \Delta z
$$

If a matrix $K$ is negative definite (semi-definite), then $x^T K x <0$ ($\leq 0$) for any $x \neq 0$. As such, if we were to find a positive definite, diagonal matrix $D(c)$ such that $D(c) M$ is negative semi-definite, we would have proved the global stability of the equilibrium. Because it is typically easier to work with symmetric matrices, wlog we can take $K = \frac{1}{2} (D(c)M + M^T D(c))$, which is exactly the same: $\Delta z^T D(c) M \Delta z = \Delta z^T K \Delta z$. 

The expression above has been used countless times to prove the stability of GLV models. Note that when our model is indeed a GLV, the $\Delta z_i$ are radially unbounded: $\Delta z_i \in [-z_i^\star, \infty)$. In this case, it therefore makes much sense to try to make $K$ negative definite.

## Stability for GLV embeddings

This is however not the case when our equations have obtained by embedding a lower-dimensional system into a larger GLV. Because we have created new "species" by combining the original species, the perturbations of the "new species" are set by the perturbations of the original species. For example, in the Leslie-Gower embedding we have that $z_3 = P / H = z_2 / z_1$, and therefore:

$$
\Delta z = 
\begin{pmatrix}
\Delta z_1\\
\Delta z_2\\
\Delta z_3
\end{pmatrix} = 
\begin{pmatrix}
\Delta z_1\\
\Delta z_2\\
\dfrac{\Delta z_2 + z_2^\star}{\Delta z_1 + z_1^\star} - \dfrac{z_2^\star}{z_1^\star}
\end{pmatrix} = 
\begin{pmatrix}
\Delta z_1\\
\Delta z_2\\
\dfrac{\Delta z_2 - \dfrac{z_2^\star}{z_1^\star} \Delta z_1}{z_1}
\end{pmatrix} 
$$

showing that the third perturbation is a function of the first two.

Computing the matrix $K$ for the system, we obtain:

## Numerical analysis


