# Random bits and pieces

## Stability of larger matrices

There are a number of techniques that can be used to prove the stability of larger systems. 

### Descartes' rule of signs

For a single-variable polynomial with real coefficients are ordered by descending variable exponent, then the number of positive roots of the polynomial is either equal to the number of sign differences between consecutive nonzero coefficients, or is less than it by an even number. Multiple roots of the same value are counted separately. As such, if a polynomial has all coefficients of the same sign, it has no positive roots. 

By considering $p(-\lambda)$ we can find the maximum number of negative roots. For example, for the Lotka-Volterra predator-prey model, we have 

$$
M = \begin{pmatrix}
0 & -\dfrac{ad}{b}\\
\dfrac{bg}{d} & 0
\end{pmatrix}
$$
The characteristic polynomial is 

$$
p(\lambda) = \lambda^2 + \dfrac{g}{d}
$$

Meaning that the number of positve roots is zero. Taking $p(-\lambda) =  (-\lambda)^2 + \dfrac{g}{d}$ which again has only positive coefficients, meaning that the number of negative roots is also zero. As such, the eigenvalues are purely imaginary (center), $\lambda = \pm i \sqrt{g / d}$.

### Routh-Hurwitz criterion

You can use the coefficients of the polynomial to determine stability. The polynomial 

$$
p(\lambda) = \lambda^2 + a_1 \lambda + a_0
$$

has all roots in the left half-plane (stable equilibrium) if $a_0 > 0$ and $a_1 > 0$. Note that, in this case $a_0 = \det(A)$ and $a_1 = -\text{tr}(A)$.

Similarly, the polynomial

$$
p(\lambda) = \lambda^3 + a_2 \lambda^2 + a_1 \lambda + a_0
$$

has roots in the left half-plane if $a_2 > 0$, $a_0 > 0$, and $a_2 a_1 > a_0$.

These conditions can be extended to larger matrices, but they become increasingly involved.

### Bounding eigenvalues using the symmetric part

Call $\lambda_1 (A)$ the eigenvalue of $A$ with the largest real part (i.e., the "rightmost" eigenvalue). Then 

$$
\Re (\lambda_1 (A)) \leq \lambda_1 ((A + A^T ) / 2)
$$

if $\lambda_1 ((A + A^T ) / 2) < 0$, then $A$ is stable, and any matrix $DA$ with $D$ diagonal and positive is stable ($D-$stability).

## Exercise

To make sure you can work with stability, consider the following model that Carlos and I are studying. We consider a simple variation on the LV predator-prey system, in which predators are divided into two classes, linked by reproduction (e.g., males and females), and each class has a different mortality rate:

$$
 \begin{cases}
    \dfrac{d x(t)}{d t} = x(t) \left(r - a \left(y^{(1)}(t) +
    y^{(2)}(t) \right) )\right)\\ \dfrac{d y^{(1)}(t)}{d t} =
    -d^{(1)}y^{(1)}(t) + \dfrac{e a x(t)}{2}\left(y^{(1)}(t) +
    y^{(2)}(t) \right) \\ \dfrac{d y^{(2)}(t)}{d t} =
    -d^{(2)}y^{(2)}(t) + \dfrac{e a x(t)}{2}\left(y^{(1)}(t) +
    y^{(2)}(t) \right)
  \end{cases}\quad. 
$$

where we take $d^{(1)} = d (1 + \epsilon)$ and $d^{(2)} = d (1 - \epsilon)$, with $|\epsilon| < 1$ to ensure that predators cannot grow by themselves. Each class of predators has its own mortality, but the reproduction term is pooled and divided equally.

The analysis of the model is simplified by considering the variables $y(t) = y^{(1)}(t) + y^{(2)}(t)$ (i.e., the total density for the predator), and $z(t) = y^{(2)}(t) - y^{(1)}(t)$ (i.e., the difference between the densities of the predator classes), yielding:

$$
  \begin{cases}
    \dfrac{d x(t)}{d t} = x(t) \left(r - a y(t))\right)\\
    \dfrac{d y(t)}{d t} = y(t) \left( -d + e a x(t) \right) + d
    \epsilon z(t)\\
    \dfrac{d z(t)}{d t} = -d z(t) + d \epsilon y(t)
  \end{cases}\quad. 
$$

Find the two equilibria of the system, and perform the stability analysis.

We describe our methods in this chapter.


## Extra

Because $M_{i,i} = 0$, we can solve for $x_i^\star$ and write:

$$
x_{i}^\star = \dfrac{\sum M_{ij}x_j^\star}{\delta + \sum M_{ij}x_j^\star} = 1 - \dfrac{\delta}{\delta + \sum M_{ij}x_j^\star} = 1 - \dfrac{1}{1 + \tau \sum M_{ij}x_j^\star}
$$

where $\tau = 1 / \delta$. We observe that a trivial solution is $x_i^\star = 0$ for all $i$ (global extinction of the population). If any $x_i^\star > 0$, then all of them must also be different from zero (and in fact, they all must be positive). Given that all $x_j^\star \leq 1$, we can write:

$$
x_{i}^\star = 1 - \dfrac{1}{1 + \tau \sum M_{ij} + \tau \sum M_{ij}(1-x_j^\star)}
$$

and therefore $0 \leq x_i^\star \leq 1 - \dfrac{1}{1 + \tau \sum M_{ij}}$.
