--- 
title: "Theoretical Community Ecology"
author: "Stefano Allesina"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "A graduate course in theoretical community ecology focusing on systems with multiple species."
---
# Preliminaries {-}

## Approach and target audience {-}

The material was prepared for the graduate class *Theoretical Community Ecology* taught at the University of Chicago --- AY 2020/2021. Following the material requires some familiarity with calculus (multivariable integration, derivatives, chain rule) and linear algebra (vector spaces, eigenvalues, eigenvectors). Also, a good working knowledge of `R` (writing functions, working with the packages `deSolve` and `tidyverse`) is needed to follow the code (all figures are generated at runtime, and therefore the source code for these lectures contains all the code/data needed to replicate the figures).

The approach taken throughout the course is to alternate between code/simulations and mathematical derivations. While several theorems are (informally) stated, proofs are included only when elementary and/or informative of the underlying biological processes.

The class builds upon material typically presented in classes on population, community and theoretical ecology.

## Topics {-}

The choice of themes is very opinionated, and heavily biased toward my own research interests. Because of this, the focus is squarely on continuous time, time-invariant models---in most cases without any consideration of space and stochasticity. Similarly, the material mostly deals with the case of multispecies dynamics, though low-dimensional models are considered when their analysis helps with the understanding of the multispecies case. Finally, much of the material is centered around the Generalized Lotka-Volterra model and its cousins (e.g., the replicator equation). This because a) the Generalized Lotka-Volterra model for multiple interacting species is in a way the simplest nonlinear model for population dynamics; and b) it is a "canonical" model---in the sense that many other models can be re-cast in GLV form.

## Notation {-}

Unless specified or for obvious exceptions, Greek letters stand for scalars (i.e., real or complex numbers), lower case roman letters for vectors, and capital roman letters for matrices (as such $a_i$ or $A_{ij}$ are scalars). We typically work in $\mathbb{R}^n$ (the $n$-dimensional Euclidean space), $\mathbb{R}^n_+$ (i.e., the positive orthant of $\mathbb{R}^n$), or $\mathbb{R}^n_{0+}$ (non-negative orthant).  $D(x)$ is a diagonal matrix with $x$ on the diagonal. The matrix $A^T$ is the transpose of $A$. Whenever it is clear what I mean, I will drop the dependency on time of certain variables. 

The Generalized Lotka-Volterra model:

$$
\dfrac{d x_i(t)}{d t} = x_i(t) \left(a_i + \sum_{j} B_{ij} x_j(t) \right)
$$

can be written in compact form as:

$$
\dfrac{d x}{d t} = D(x) (a + B x)
$$

## Grading and code of conduct {-}

Students should follow the rules and regulations set out by [University policy](https://studentmanual.uchicago.edu/academic-policies/). I am expecting all students to a) participate in all classes (please contact me if you are going to be absent); b) actively contribute to discussions and lectures; c) be punctual (both for class and when submitting the homework); d) be professional and honest (no copying/cheating/plagiarizing).

### Homework (80%) {-}

Each of the lectures contains exercises that should be completed as graded homework. The homework should be submitted through Canvas as one or more `pdf` files obtained by compiling `Rmd` files. The homework should contain the derivations (you can use `LaTex` to typeset mathematics within `Rmd`, see [here](https://rpruim.github.io/s341/S19/from-class/MathinRmd.html) for commonly used commands), and code. The code must run and be correct to get a passing grade.

### Review (20%) {-}

The remaining 20% of the grade is based on a graded review. Each student should choose an interesting (important, provocative, etc.) published paper or preprint in theoretical community ecology, and produce a review (of the kind one would submit to a journal if solicited for comments). The review must contain two sections: a) Comments to the Authors, and b) Recommendation for the Editor. Good advice on writing reviews can be found [here](https://dynamicecology.wordpress.com/2013/01/03/advice-how-to-review-a-manuscript-for-a-journal/).

### Accommodation for students with disabilities {-}

University of Chicago is committed to ensuring equitable access to our academic programs and services. Students with disabilities who have been approved for the use of academic accommodations by [Student Disability Services](https://disabilities.uchicago.edu/) (SDS) and need a reasonable accommodation(s) to participate fully in this course should follow the procedures established by SDS for using accommodations. Timely notifications are required in order to ensure that your accommodations can be implemented. Please meet with me to discuss your access needs in this course after you have completed the SDS procedures for requesting accommodations.

## A note about biographies {-}

The lecture notes are interdispersed with short biographies of scientists who greatly contributed to the problems being studied. The attentive reader will notice that the photographs are depicting a long sequence of old white men. Their age is easy to explain: I have only included biographies of deceased scientists (so that they cannot contradict me!), and most of them enjoyed a long life (with some exceptions; for example Robert MacArthur tragically died at age 45). The impossibly skewed gender ratio, and the lack of ethnic diversity has to be explained with the tremendous homogeneity of the field---which was broken only recently. It is my hope that these lectures will engage young ecologists from different backgrounds and histories with the theory of community ecology, such that whoever will teach this type of material in a couple of decades will be able to include a more interesting and diverse gallery of portraits. 

## Sources {-}

Many excellent books are available on these topics. Here are the main references I've used while preparing these lectures:

- @strogatz2018nonlinear --- a clear, concise introduction to dynamical systems.
- @ellner2011dynamic --- an introduction to dynamical models focusing on biology.
- @hofbauer1998evolutionary --- a great resource for models of population dynamics and evolutionary game theory.
- @szederkenyi2018analysis --- an introduction to quasi-polynomial systems and reaction networks.
- @hadeler2017topics --- a more mathematically-focused reading.
- @hirsch2012differential --- an extensive, clearly written and rigorous introduction to dynamical systems.

## Acknowledgements {-}

These lectures grew out of a set of four lectures I have presented at the ICTP-SAIFR/IFT-UNESP ["School on Community Ecology: from patterns to principles"](https://www.ictp-saifr.org/community-ecology-from-patterns-to-principles/), held on January 20-25, 2020 in São Paulo, Brazil. Thanks to the organizers (Marcus Aguiar, Jacopo Grilli, Roberto Kraenkel, Ricardo Martinez-Garcia and Paulo Inácio Prado) for the invitation and for prompting me to start working on the material. 
The lecture on assembly was test-driven at the ICTP ["Winter School on Quantitative Systems Biology: Quantitative Approaches in Ecosystem Ecology"](https://indico.ictp.it/event/9131/), organized by Simon Levin, Matteo Marsili, Jacopo Grilli, and Antonio Celani. I am grateful to the students in both schools for useful feedback. 

The development of this material was supported by the National Science Foundation ([DEB #2022742](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2022742)). Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author and do not necessarily reflect the views of the National Science Foundation.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
